### PR TITLE
WIP - caching for features

### PR DESCRIPTION
**Pull request by cmacdonald**
Addresses #17

### CODE REVIEW

**Comment by cmacdonald** [comment]
q: why use pickle.loads() etc if using a BLOB datatype. Shouldnt we be able to get the _binary_ representation rather than dumps/loads (string)?

**Comment by cmacdonald** [comment]
sweet

**Comment by seanmacavaney** [comment]
I think this is all set to merge?

**Comment by cmacdonald** [comment]
perfect, thanks! I already started using it for an IR class notebook

**Pull request merged**
